version: "3.6"
#all port number should be exposed appending 9
services:

  kanboard:
    image: kanboard/kanboard:latest
    container_name: kanboard
    restart: unless-stopped
    ports:
      - "6443:443"
    depends_on:
      - kanboard-db
    volumes:
      - /home/cevasrv/data/kanboard/data:/var/www/app/data
      - /home/cevasrv/data/kanboard/plugins:/var/www/app/plugins
      - /home/cevasrv/data/kanboard/ssl:/etc/nginx/ssl
      - /home/cevasrv/Workspace/kanboard/config/config.default.php:/var/www/app/config.default.php
      - /home/cevasrv/Workspace/kanboard/config/config.php:/var/www/app/config.php
      - /home/cevasrv/Workspace/kanboard/ssl/kanboard.crt:/etc/nginx/ssl/kanboard.crt
      - /home/cevasrv/Workspace/kanboard/ssl/kanboard.key:/etc/nginx/ssl/kanboard.key
    environment:
      PLUGIN_INSTALLER: true
      DATABASE_URL: mysql://kanboard:KanBoardDB@kanboard-db/kanboard
      #DATABASE_URL: postgres://postgres:postgres@kanboard-db:5432/kanboard
    networks:
      - portainer

  kanboard-db:
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /home/cevasrv/data/kanboard/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: MySQL
      MYSQL_DATABASE: kanboard
      MYSQL_USER: kanboard
      MYSQL_PASSWORD: KanBoardDB
    networks:
      - portainer

volumes:
  kanboard:

networks:
  portainer:
    name: portainer
    external: true
