version: '3.7'
services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:14.1-alpine
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ${DATA}/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_USER=${USERNAME}
      - POSTGRES_DB=${DATABASE}
    networks:
      - portainer

  pgadmin:
    container_name: pgadmin4
    hostname: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: deebendu.kumar@espire.com
      PGADMIN_DEFAULT_PASSWORD: Reset@123
    volumes:
      - ${DATA}/erds:/erds
    ports:
      - "5050:5050"
    networks:
      - portainer

networks:
  portainer:
    name: portainer
    external: true