version: '3.7'
services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:14.1-alpine
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ${DATA}/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_USER=${USERNAME}
      - POSTGRES_DB=${DATABASE}
    networks:
      - portainer

networks:
  portainer:
    name: portainer
    external: true