#------------------------------------------------------------------------------
# Author: Deebendu Kumar
# Created: 17-10-2023
# Copyright 2023 by Espire Infolabs
#------------------------------------------------------------------------------
version: '3'
services:
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    restart: unless-stopped
    hostname: redis-commander
    network_mode: bridge
    ports:
      - 8081:8081/tcp
    environment:
      REDIS_HOSTS: redis1:192.0.2.1:6379:0:changeme
networks:
  portainer:
    name: portainer
    external: true