#------------------------------------------------------------------------------
# Author: Deebendu Kumar
# Created: 17-10-2023
# Copyright 2023 by Espire Infolabs
#------------------------------------------------------------------------------
version: '3'
#all port number should be exposed appending
services:

  muuvr:
    image: deebendu/muuvr:latest
    container_name: muuvr
    restart: on-failure
    ports:
      - "8080:8080"
    volumes:
      - ${DATA}/app/config:/opt/service/config
    networks:
      - portainer

networks:
  portainer:
    name: portainer
    external: true
