#------------------------------------------------------------------------------
# Author: Deebendu Kumar
# Created: 17-10-2023
# Copyright 2023 by Espire Infolabs
#------------------------------------------------------------------------------
version: '3'
services:
  memcached:
    image: memcached:1.5.19-alpine
    container_name: memcached
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 11211:11211/tcp
networks:
  portainer:
    name: portainer
    external: true