#------------------------------------------------------------------------------
# Author: Deebendu Kumar
# Created: 17-10-2023
# Copyright 2023 by Espire Infolabs
#------------------------------------------------------------------------------
version: '3'
#all port number should be exposed appending 9
services:

  mariadb:
    image: library/mariadb:10
    container_name: mariadb
    volumes:
      - ${DATA}/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: KeycloakDB
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]
    networks:
      - portainer

  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    container_name: keycloak
    volumes:
      #- ${DATA}/keycloak:/opt/jboss/keycloak
      - ./certs:/opt/jboss/keycloak/certs
    ports:
      - "6443:8443"
    environment:
      DB_VENDOR: mariadb
      DB_ADDR: mariadb
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: KeycloakDB
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING
      KC_HOSTNAME_STRICT_HTTPS: false
#      KC_HTTPS_CERTIFICATE_FILE: /opt/jboss/keycloak/certs/eunica.crt
#      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/jboss/keycloak/certs/eunica.key
    depends_on:
      - mariadb
    networks:
      - portainer

networks:
  portainer:
    name: portainer
    external: true
