#------------------------------------------------------------------------------
# Author: Deebendu Kumar
# Created: 17-10-2023
# Copyright 2023 by Espire Infolabs
#------------------------------------------------------------------------------
version: '3'
#all port number should be exposed appending 9
services:

  mariadb:
    image: library/mariadb:10
    container_name: mariadb
    volumes:
      - ${DATA}/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: KeycloakDB
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]
    networks:
      - portainer

  keycloak:
    image: bitnami/keycloak:22.0.1
    container_name: keycloak
    restart: unless-stopped
    volumes:
      - ./certs:/opt/jboss/keycloak/certs
    ports:
      - "6443:8443"
    environment:
      KEYCLOAK_DATABASE_VENDOR: mariadb
      KEYCLOAK_DATABASE_HOST: mariadb
      KEYCLOAK_DATABASE_PORT: 3306
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_USER: keycloak
      KEYCLOAK_DATABASE_PASSWORD: KeycloakDB
      KEYCLOAK_DATABASE_SCHEMA: public
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd
      KEYCLOAK_ENABLE_HEALTH_ENDPOINTS: 'true'
      KEYCLOAK_ENABLE_STATISTICS: 'true'
      KC_HOSTNAME: auth.espire.com
      KC_PROXY: edge
      KC_PROXY_ADDRESS_FORWARDING: 'true'
      KC_HTTP_ENABLED: 'true'
#      DB_VENDOR: mariadb
#      DB_ADDR: mariadb
#      DB_DATABASE: keycloak
#      DB_USER: keycloak
#      DB_PASSWORD: KeycloakDB
#      KEYCLOAK_USER: admin
#      KEYCLOAK_PASSWORD: Pa55w0rd
#      JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING
#      KC_HOSTNAME_STRICT_HTTPS: false
#      KC_HTTPS_CERTIFICATE_FILE: /opt/jboss/keycloak/certs/eunica.crt
#      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/jboss/keycloak/certs/eunica.key
    depends_on:
      - mariadb
    networks:
      - portainer

networks:
  portainer:
    name: portainer
    external: true
