#------------------------------------------------------------------------------
# Author: Deebendu Kumar
# Created: 17-10-2023
# Copyright 2023 by Espire Infolabs
#------------------------------------------------------------------------------
version: '3'
#all port number should be exposed appending 9
services:

  apim:
    image: deebendu/apim:latest
    container_name: apim
    restart: on-failure
    ports:
      - "8765:8765"
    volumes:
      - ${DATA}/gateway/config:/opt/service/config
      - ${DATA}/gateway/certs:/lib/jvm/java-11-openjdk-amd64/jre/lib/security
      - ${DATA}/gateway/trace:/opt/service/trace
    networks:
      - portainer

  apim-admin:
    image: deebendu/apim-admin:latest
    container_name: apim-admin
    restart: on-failure
    ports:
      - "8022:8022"
    volumes:
      - ${DATA}/admin/config:/opt/service/config
      - ${DATA}/admin/certs:/opt/service/certs
      - ${DATA}/admin/trace:/opt/service/trace
    networks:
      - portainer

networks:
  portainer:
    name: portainer
    external: true
