#------------------------------------------------------------------------------
# Author: Deebendu Kumar
# Created: 17-10-2023
# Copyright 2023 by Espire Infolabs
#------------------------------------------------------------------------------
version: '3'
#all port number should be exposed appending 9
services:

  apim:
    image: deebendu/apim:latest
    container_name: apim
    restart: on-failure
    ports:
      - "8765:8765"
    volumes:
      - ${DATA}/gateway/config:/opt/service/config
    networks:
      - portainer

  apim-admin:
    image: deebendu/apim-admin:1.0.1
    container_name: apim-admin
    restart: on-failure
    ports:
      - "8022:8022"
    volumes:
      - ${DATA}/admin/config:/opt/service/config
    networks:
      - portainer

networks:
  portainer:
    name: portainer
    external: true
