#------------------------------------------------------------------------------
# Author: Deebendu Kumar
# Created: 17-10-2023
# Copyright 2023 by Espire Infolabs
#------------------------------------------------------------------------------
version: '3'
#all port number should be exposed appending 9
services:
  gitlab:
    image: gitlab/gitlab-ce:16.5.2-ce.0
    container_name: gitlab
    restart: unless-stopped
    privileged: true
    hostname: '172.187.226.194'
    ports:
      - "8888:8888"
      - "2224:22"
    volumes:
      - ${DATA}/config:/etc/gitlab
      - ${DATA}/logs:/var/log/gitlab
      - ${DATA}/data:/var/opt/gitlab
      - ${DATA}/certs:/etc/gitlab/ssl
    environment:
      GITLAB_ROOT_PASSWORD: "MySecretPassword"
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://172.187.226.194:8888'
        nginx['listen_port'] = 8888
        nginx['ssl_certificate'] = "/etc/gitlab/ssl/server-cert.pem"
        nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/server-key.pem"
        nginx['ssl_protocols'] = "TLSv1.1 TLSv1.2"
        nginx['redirect_http_to_https'] = true
    shm_size: '1024m'
    networks:
      - portainer
networks:
  portainer:
    name: portainer
    external: true
