version: '3'
services:
  mongodb:
    image: mongo:4.0
    hostname: ${MONGODB_CONTAINER_NAME}
    container_name: ${MONGODB_CONTAINER_NAME}
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - ${DATA}/mongo:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - portainer

networks:
  portainer:
    name: portainer
    external: true