#------------------------------------------------------------------------------
# Author: Deebendu Kumar
# Created: 17-10-2023
# Copyright 2023 by Espire Infolabs
#------------------------------------------------------------------------------
version: '3'

services:
  consul:
    image: hashicorp/consul:latest
    container_name: consul
    ports:
      - "8500:8500"
    networks:
      - portainer

networks:
  portainer:
    external: true
