version: "3"
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    restart: always
    environment:
      - node.name=elasticsearch
      - thread_pool.search.queue_size=500
      - processors=1
      - discovery.type=single-node
    ports:
      - '9200:9200'
    mem_limit: 4g
    volumes:
      - /data/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - portainer

  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.1
    container_name: kibana
    ports:
      - '5601:5601'
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - portainer
    depends_on:
      - elasticsearch

networks:
  portainer:
    name: portainer
    external: true
