version: '3'
services:
  apim-mysql:
    container_name: apim-mysql
    image: library/mariadb:10.1
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ${DATA}/mysql:/var/lib/mysql
      - ${DATA}/mysql/scripts:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: apim
      MYSQL_USER: apim
      MYSQL_PASSWORD: apimrw
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]
    networks:
      - portainer

#  apim-analytics:
#    container_name: apim-analytics
#    image: wso2/wso2am-analytics-worker:2.6.0
#    restart: on-failure
#    volumes:
#      - ./apim-analytics:/home/wso2carbon/wso2-config-volume
#    ports:
#      - "19091:9091"
#      - "19444:9444"
#    depends_on:
#      - apim-mysql
#    networks:
#      - portainer
#
  apim:
    container_name: apim
    image: wso2/wso2am:3.1.0
    restart: always
    #volumes:
      #- ${DATA}/wso2am-2.6.0/repository:/home/wso2carbon/wso2am-2.6.0/repository
      #- ${DATA}/wso2-config-volume:/home/wso2-config-volume
    ports:
      - "19763:9763"
      - "19443:9443"
      - "18280:8280"
      - "18243:8243"
    depends_on:
      - apim-mysql
    networks:
      - portainer

networks:
  portainer:
    name: portainer
    external: true

