version: '3'
#all port number should be exposed appending 9
services:

  activemq:
    image: zesticio/activemq:5.15.12
    container_name: activemq
    restart: always
    ports:
      - "8161:8161"
      - "61616:61616"
    volumes:
      - ${DATA}/data:/opt/apache-activemq-5.15.12/data
    networks:
      - portainer

networks:
  portainer:
    name: portainer
    external: true