#------------------------------------------------------------------------------
# Author: Deebendu Kumar
# Created: 17-10-2023
# Copyright 2023 by Espire Infolabs
#------------------------------------------------------------------------------
version: '3'
services:
  nginx:
    image: nginx:1.17.3
    container_name: nginx
    restart: unless-stopped
    hostname: nginx
    network_mode: bridge
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - /etc/nginx:/etc/nginx
    #environment:
networks:
  portainer:
    name: portainer
    external: true