#------------------------------------------------------------------------------
# Author: Deebendu Kumar
# Created: 17-10-2023
# Copyright 2023 by Espire Infolabs
#------------------------------------------------------------------------------
version: '3'
services:
  jenkins:
    image: jenkins/jenkins:2.204
    container_name: jenkins
    restart: unless-stopped
    hostname: jenkins
    network_mode: bridge
    ports:
      - "8080:8080/tcp"
    volumes:
      - /var/lib/jenkins:/var/jenkins_home
    #environment:

networks:
  portainer:
    name: portainer
    external: true