#------------------------------------------------------------------------------
# Author: Lavi Jain
# Created: 09-02-2024
# Copyright 2024 by Espire Infolabs
#------------------------------------------------------------------------------
version: '3'
#all port number should be exposed appending
services:

  react-apim:
    image: deebendu/react-apim:latest
    container_name: react-apim
    restart: on-failure
    ports:
      - "80:80"
    networks:
      - portainer

networks:
  portainer:
    name: portainer
    external: true
