version: '3'
services:
  chromadb:
    container_name: chromadb
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      # Be aware that indexed data are located in "/chroma/chroma/"
      # Default configuration for persist_directory in chromadb/config.py
      # Read more about deployments: https://docs.trychroma.com/deployment
      - /data/chromadb:/chroma/chroma
    command: "--workers 1 --host 0.0.0.0 --port 8000 --proxy-headers --log-config chromadb/log_config.yml --timeout-keep-alive 30"
    environment:
      - IS_PERSISTENT=TRUE
    restart: unless-stopped # possible values are: "no", always", "on-failure", "unless-stopped"
    ports:
      - "8000:8000"
    healthcheck:
      # Adjust below to match your container port
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - portainer

  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    restart: unless-stopped # possible values are: "no", always", "on-failure", "unless-stopped"
    volumes:
      - /data/ollama:/root/.ollama
    ports:
      - "11434:11434"
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [ gpu ]
    networks:
      - portainer

  ollamaui:
    container_name: ollamaui
    image: ghcr.io/ollama-webui/ollama-webui:main
    restart: unless-stopped # possible values are: "no", always", "on-failure", "unless-stopped"
    volumes:
      - /data/ollamaui:/app/backend/data
    ports:
      - "3010:8080"
    environment:
      - OLLAMA_API_BASE_URL=http://192.168.1.151:11434/api
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - portainer

networks:
  portainer:
    name: portainer
    external: true
