#------------------------------------------------------------------------------
# Author: Deebendu Kumar
# Created: 17-10-2023
# Copyright 2023 by Espire Infolabs
#------------------------------------------------------------------------------
version: '3'
services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    hostname: redis
    ports:
      - 6379:6379/tcp
    volumes:
      - /opt/redis/data:/data
      - /opt/redis/conf:/usr/local/etc/redis/redis.conf
    networks:
      - portainer

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    restart: unless-stopped
    hostname: redis-commander
    ports:
      - 8081:8081/tcp
    environment:
      REDIS_HOSTS: redis1:192.0.2.1:6379:0:changeme
    networks:
      - portainer

networks:
  portainer:
    name: portainer
    external: true